spring.application.name=demo

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none
springdoc.api-docs.enabled=true

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/receipiti?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:yubin1579$}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Kakao OAuth2
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_KEY}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_SECRET_KEY}
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname, account_email

# Provider
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# Kakao Local API
kakao.local.rest-api-key=${KAKAO_LOCAL_REST_API_KEY:${KAKAO_KEY}}

spring.jackson.deserialization.fail-on-unknown-properties=false
spring.mvc.throw-exception-if-no-handler-found=true
logging.level.org.springframework.web=DEBUG

# JWT
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=3600000

oauth2.redirect-url=${OAUTH2_APP_REDIRECT_URL:receipiti://auth/kakao}
oauth2.login-code-expiration-seconds=120
oauth2.authorization-request-expiration-seconds=300
server.forward-headers-strategy=framework

# Naver Clova OCR Configuration
naver.ocr.secret=${NAVER_OCR_SECRET_KEY}
naver.ocr.url=${NAVER_OCR_INVOKE_URL}

# Google Gemini LLM
gemini.api.key=${GEMINI_API_KEY}
